- name: Check UUID was overridden
  ansible.builtin.assert:
    that: "signalilo_uuid != '00000000-0000-0000-0000-000000000000'"
    fail_msg: "Set Signalilo UUID to new value"

- name: Copy signalilo binary from Docker image
  ansible.builtin.import_tasks: docker.yml
  when: signalilo_from == 'docker'

- name: Build signalilo binary from source
  ansible.builtin.import_tasks: source.yml
  when: signalilo_from == 'source'

- name: Ensure group signalilo exists
  ansible.builtin.group:
    name: signalilo
    state: present
  become: true

- name: Add the user signalilo
  ansible.builtin.user:
    name: signalilo
    comment: Signalilo service user
    shell: /usr/sbin/nologin
    group: signalilo
  become: true

- name: Create environment configuration file
  ansible.builtin.template:
    src: signalilo.env.j2
    dest: /usr/local/etc/signalilo.env
    owner: signalilo
    group: signalilo
    mode: "0640"
  become: true
  notify:
    - Restart Signalilo

- name: Create file with bearer token for alertmanager authentication
  ansible.builtin.copy:
    content: "{{ signalilo_alertmanager_bearer_token }}"
    dest: "{{ signalilo_bearer_token_path }}"
    owner: root
    group: root
    mode: "0640"
  become: true

- name: Copy systemd service
  ansible.builtin.copy:
    src: signalilo.service
    dest: /etc/systemd/system/signalilo.service
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Start Signalilo
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: signalilo
    daemon_reload: true
  become: true
